AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PoliTopics - unified Lambda + DynamoDB + S3 (error logs) + daily schedule

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        TABLE_NAME: !Ref PolitopicsTable
        ERROR_BUCKET: !Ref ErrorBucket
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

Resources:
  PolitopicsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: politopics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ErrorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub politopics-error-logs-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: expire-after-90-days
            Status: Enabled
            ExpirationInDays: 90

  PolitopicsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: politopics-handler
      Handler: dist/lambda_handler.handler
      CodeUri: .
      Description: Fetch National Diet records, summarize via LLM, and store to DynamoDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PolitopicsTable
        - S3WritePolicy:
            BucketName: !Ref ErrorBucket
        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: "*"
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: politopics-daily
            Description: Daily run to fetch & summarize
            Enabled: true

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST

  InvokeRoute:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: politopics-http-invoke
      Handler: dist/lambda_handler.handler
      CodeUri: .
      Description: HTTP trigger for on-demand runs (calls the same handler)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PolitopicsTable
        - S3WritePolicy:
            BucketName: !Ref ErrorBucket
      Events:
        ApiPost:
          Type: HttpApi
          Properties:
            Path: /run
            Method: POST
            ApiId: !Ref HttpApi

Outputs:
  TableName:
    Value: !Ref PolitopicsTable
  ErrorBucketName:
    Value: !Ref ErrorBucket
  FunctionName:
    Value: !Ref PolitopicsFunction
  HttpApiUrl:
    Description: Base URL for the HTTP API
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
