Parameters:
  NationalDietApiEndpoint:
    Type: String
  GeminiApiKey:
    Type: String
  AwsDynamoDbEndpoint:
    Type: String

Resources:
  ScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "PoliTopics-C"
      Handler: lambda_handler.handler
      Runtime: nodejs22.x
      CodeUri: dist/
      MemorySize: 128
      Timeout: 60
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
