Parameters:
  NationalDietApiEndpoint:
    Type: String
  GeminiApiKey:
    Type: String
  AwsDynamoDbEndpoint:
    Type: String

Resources:
  ScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "PoliTopics-C"
      Handler: lambda_handler.handler
      Runtime: nodejs22.x
      CodeUri: dist/
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          NATIONAL_DIET_API_ENDPOINT: !Ref NationalDietApiEndpoint
          GEMINI_API_KEY: !Ref GeminiApiKey
          AWS_DYNAMODB_ENDPOINT: !Ref AwsDynamoDbEndpoint
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
